### PR TITLE
fix: dynamically adjust NLJ output batch size and optimize NLJ with single build vector

### LINKED ISSUE #401: [Bug] NestedLoopJoinProbe OOM with wide build-side rows
### Component Selection

- [x] Core Engine (Expression eval, Memory, Vector)
- [ ] Connectors / File Formats (Hive, Parquet, etc.)
- [ ] API / Bindings (Python, etc.)
- [ ] Build
- [ ] Other

### Describe the Bug

This issue occurs in a Spark instance when the NLJ (Nested Loop Join) build side contains only one row with an array<string> column, the probe side also contains an array<string> column, both columns have large data sizes, and a join filter is present.

In the latest NLJ code, the probe dictionary vector is allocated with a fixed size (32768 in Spark on Bolt) and filled with zeros. When the average row size on the probe side is large, the flat size is computed based on the probe dictionary's size, resulting in an excessively large flat size. Furthermore, during exportToArrow, the inner probe vector is converted to an Arrow array with its full length, which causes OOM.

Additionally, when a filter is present, the join probe selects one row at a time to perform a cross product with the build vector. It constructs a single-row vector, applies the filter on it, and then copies this single-row vector into the final output vector. This row-by-row approach significantly degrades performance.

### Reproduction Steps

1. Create a build table with 4 rows, each containing an `ARRAY<VARCHAR>` column with 200 elements of ~500-byte strings (~100KB per row).
2. Create a probe table with 1000 rows.
3. Execute a NestedLoopJoin with a join condition (e.g., `t0 = u0`).
4. Set memory pool cap to 50MB.
5. Observe OOM in `copyBuildValues` → `ArrayVectorBase::copyRangesImpl` → `FlatVector<StringView>::resize` → `AlignedBuffer::reallocate`.

### Bolt Version / Commit ID

dc0bebf

### System Configuration

```markdown
- **OS**: Linux (Ubuntu / CentOS)
- **Compiler**: GCC 11+
- **Build Type**: Debug / Release
- **CPU Arch**: x86_64
- **Framework**: Spark (via Gluten)
```

### Logs / Stack Trace

```shell
I20260319 19:27:35.653000 140190953764544 NestedLoopJoinProbe.cpp:189] NestedLoopJoinProbe::addInput, size: 343, flatSize: 12411877
I20260319 19:27:35.866150 140190953764544 NestedLoopJoinProbe.cpp:274] return output, size: 343, flat size: 682812391, ROW<n1_6:VARCHAR,n1_7:ARRAY<VARCHAR>,n1_8:BIGINT,n1_9:BIGINT,n2_0:ARRAY<VARCHAR>>
I20260319 19:27:35.866411 140190953764544 NestedLoopJoinProbe.cpp:276] 0, flat size: 19938229
I20260319 19:27:35.866421 140190953764544 NestedLoopJoinProbe.cpp:276] 1, flat size: 538683756
I20260319 19:27:35.866428 140190953764544 NestedLoopJoinProbe.cpp:276] 2, flat size: 284307
I20260319 19:27:35.866434 140190953764544 NestedLoopJoinProbe.cpp:276] 3, flat size: 284307
I20260319 19:27:35.866440 140190953764544 NestedLoopJoinProbe.cpp:276] 4, flat size: 123621792
I20260319 19:27:35.874381 140190953764544 BoltColumnarBatch.cc:69] export schema before flatten: 343, flat size: 662305548
I20260319 19:27:35.874501 140190953764544 BoltColumnarBatch.cc:71] [DICTIONARY ARRAY<VARCHAR>: 32768 elements, no nulls], [ARRAY ARRAY<VARCHAR>: 343 elements, no nulls]
I20260319 19:27:35.874526 140190953764544 BoltColumnarBatch.cc:72] encoding: DICTIONARY, flat size: 538683756
I20260319 19:27:35.874532 140190953764544 BoltColumnarBatch.cc:71] [ARRAY ARRAY<VARCHAR>: 32768 elements, no nulls]
I20260319 19:27:35.874540 140190953764544 BoltColumnarBatch.cc:72] encoding: ARRAY, flat size: 123621792
I20260319 19:27:36.070304 140190985221824 PageReader.cpp:795] preloadRepDefs[0x7f80c1420200] : def/rep levels = 514768, avgPageLen = 85885, chunkSize = 47284467, pagesCntPerBatch = 163, samplePages = 10, repDefMemoryLimit_ 16777216
I20260319 19:27:36.522121 140190985221824 NestedLoopJoinProbe.cpp:189] NestedLoopJoinProbe::addInput, size: 256, flatSize: 8796992
I20260319 19:27:36.577080 140190953764544 BoltColumnarBatch.cc:75] export schema after flatten: 343, flat size: 661153552
I20260319 19:27:36.577209 140190953764544 BoltColumnarBatch.cc:77] encoding: ARRAY, flat size: 537922040
I20260319 19:27:36.577217 140190953764544 BoltColumnarBatch.cc:77] encoding: ARRAY, flat size: 123231512
I20260319 19:27:36.659053 140190953764544 Bridge.cpp:1052] export string size: 31626019, buffer size: 1285864778
```

### Expected Behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by zhangxffff**
### What problem does this PR solve?

This issue occurs in a Spark instance when the NLJ (Nested Loop Join) build side contains only one row with an `array<string>` column, the probe side also contains an `array<string>` column, both columns have large data sizes, and a join filter is present.

In the latest NLJ code, the probe dictionary vector is allocated with a fixed size (32768 in Spark on Bolt) and filled with zeros. When the average row size on the probe side is large, the flat size is computed based on the probe dictionary's size, resulting in an excessively large flat size. Furthermore, during `exportToArrow`, the inner probe vector is converted to an Arrow array with its full length, which causes OOM.

Additionally, when a filter is present, the join probe selects one row at a time to perform a cross product with the build vector. It constructs a single-row vector, applies the filter on it, and then copies this single-row vector into the final output vector. This row-by-row approach significantly degrades performance.

Issue Number: close #401 

### Type of Change

- [ ] 🐛 Bug fix (non-breaking change which fixes an issue)
- [ ] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🚀 Performance improvement (optimization)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🔨 Refactoring (no logic changes)
- [ ] 🔧 Build/CI or Infrastructure changes
- [ ] 📝 Documentation only

### Description

This PR addresses the OOM and performance issues in NLJ when handling wide probe/build rows with a filter.

1. Compute the average row size of probe and build inputs to determine a proper batch size, avoiding OOM.
2. Generate larger cross-product batches for NLJ with filters to improve performance.

#### Batch Size Estimator

During `prepareOutput`, the probe creates a dictionary vector based on `outputBatchSize_`. Before vector creation, we now update `outputBatchSize_` using the average row size (sum of probe row size and build row size). This keeps the output vector's memory consumption under control and avoids OOM in downstream operators.

#### Single Build Row and Single Build Vector Optimization for NLJ with Filter

In the current NLJ implementation, when a filter is present, `getNextCrossProductBatch` returns (1 probe row) × (build vector) for subsequent filter processing. However, when the build vector is small (or even a single row), this results in returning a single-row vector for filtering, causing a performance issue.

To address this, we now return (batchSize / buildSize probe rows) × (build vector) from `getNextCrossProductBatch`. In the subsequent evaluation loop, we replace the single probe row loop with one that supports iterating over a probe × build dictionary. Since there is only one probe vector and one build vector, we can also avoid the copy in `CopyBuildValues` and simply return a dictionary vector instead.

### Performance Impact

- [x] **No Impact**: This change does not affect the critical path (e.g., build system, doc, error handling).
- [x] **Positive Impact**: I have run benchmarks.
    <details>
    <summary>Click to view Benchmark Results</summary>

    ```text
   NLJ before optmization: 4.68h
   NLJ after optimization: 1.4min
    ```
    </details>
- [ ] **Negative Impact**: Explained below (e.g., trade-off for correctness).

### Release Note

Please describe the changes in this PR

Release Note:

```text
Release Note:
- Fixed a crash in `substr` when input is null.
- optimized `group by` performance by 20%.
```

### Checklist (For Author)

- [x] I have added/updated unit tests (ctest).
- [x] I have verified the code with local build (Release/Debug).
- [x] I have run clang-format / linters.
- [ ] (Optional) I have run Sanitizers (ASAN/TSAN) locally for complex C++ changes.
- [ ] No need to test or manual test.

### Breaking Changes

- [ ] No
- [ ] Yes (Description: ...)
    <details>
    <summary>Click to view Breaking Changes</summary>

    ```text
    Breaking Changes:
    - Description of the breaking change.
    - Possible solutions or workarounds.
    - Any other relevant information.
    ```
    </details>

### CODE REVIEW

File: bolt/exec/NestedLoopJoinProbe.cpp [hunk 1]
```diff
@@ -639,19 +713,26 @@ void NestedLoopJoinProbe::addOutputRow(vector_size_t buildRow) {
...
+      buildCopyRanges_.push_back({buildRow, numOutputRows_, 1});
+    }
   }
 }
 
 void NestedLoopJoinProbe::copyBuildValues(const RowVectorPtr& buildVector) {
-  if (buildCopyRanges_.empty() || isLeftSemiProjectJoin(joinType_)) {
+  if (buildCopyRanges_.empty() || isLeftSemiProjectJoin(joinType_) ||
+      useBuildDictionary()) {
+    // Dictionary mode: indices already set in addOutputRow(), no copy needed.
```
Comment (markjin1990) [inline bolt/exec/NestedLoopJoinProbe.cpp]: Shall we clear `buildCopyRanges_` when (isLeftSemiProjectJoin(joinType_) || useBuildDictionary())?

Comment (zhangxffff) [reply bolt/exec/NestedLoopJoinProbe.cpp]: When `useBuildDictionary()` is true, `buildCopyRanges_` is never populated and remains empty. However, when `isLeftSemiProjectJoin(joinType_)` is true, `buildCopyRanges_` was still being appended to and would grow unboundedly without an explicit `clear()`. The latest commit fixes the issue by suppressing `push_back` into `buildCopyRanges_` for the `isLeftSemiProjectJoin` case as well, ensuring `buildCopyRanges_` is always kept empty whenever `isLeftSemiProjectJoin(joinType_) || useBuildDictionary()`.
