### PR TITLE
fix: accurate estimateFlatSize for FlatVector<StringView> that flatten from dictionary

### LINKED ISSUE #406: [Bug] Shuffle writer OOM due to estimateFlatSize() underestimation with shared string buffers
### Component Selection

- [x] Core Engine (Expression eval, Memory, Vector)
- [ ] Connectors / File Formats (Hive, Parquet, etc.)
- [ ] API / Bindings (Python, etc.)
- [ ] Build
- [ ] Other

### Describe the Bug

Shuffle writer V1/V2 uses `estimateFlatSize()` to decide whether to split large batches (`splitExtremelyLargeBatch`) and when to trigger spill. However, `estimateFlatSize()` severely underestimates the actual data size when multiple row share the same string buffer in one column. As a result, `splitExtremelyLargeBatch` does not trigger when it should, and the full oversized batch goes through `splitSingleBatch` where `splitBinaryType` attempts to allocate the actual data size, causing OOM.

### Reproduction Steps

1. Run a Spark shuffle stage reading Parquet files with large VARCHAR/VARBINARY columns
2. The batch contains ~7000 rows with binary data totaling ~2GB+
3. `estimateFlatSize()` reports ~44MB due to shared Parquet page buffers
4. Shuffle writer does not split the batch, attempts to allocate full partition buffers
5. OOM: `Failed to allocateBytes 2.27GB: Exceeded memory pool cap

### Bolt Version / Commit ID

dc0bebf

### System Configuration

```markdown
- **OS**: (e.g. Ubuntu 22.04, CentOS 7)
- **Compiler**: (e.g. GCC 11, Clang 14)
- **Build Type**: (Debug / Release / RelWithDebInfo)
- **CPU Arch**: (e.g. x86_64 AVX2, ARM64)
- **Framework**: (e.g. Spark 3.3, PrestoDB)
```

### Logs / Stack Trace

```shell
W20260402 11:31:21.629583 140562938197696 TableScan.cpp:457] TableScan large string batch: rows=7168 estimateFlatSize=62814897 usedSize=58540976 actualStringBytes=1662702549 ratio=26x maxSingleStr=230859 numStringCols=36 readBatchSize=7168
W20260402 11:31:21.629824 140562938197696 TableScan.cpp:537]   col[1] n0_1 encoding=DICTIONARY leafSize=11 leafRetained=384 actualBytes=21504 row{min=3 max=3 med=3 avg=3 cnt=7168} dict{min=3 max=3 med=3 avg=3 cnt=11}
W20260402 11:31:21.630262 140562938197696 TableScan.cpp:537]   col[2] n0_2 encoding=FLAT leafSize=7168 leafRetained=524000 actualBytes=301736 row{min=12 max=80 med=47 avg=42 cnt=7168} dict{min=12 max=80 med=47 avg=42 cnt=7168}
W20260402 11:31:21.630408 140562938197696 TableScan.cpp:537]   col[3] n0_3 encoding=DICTIONARY leafSize=14 leafRetained=448 actualBytes=43008 row{min=6 max=6 med=6 avg=6 cnt=7168} dict{min=6 max=6 med=6 avg=6 cnt=14}
W20260402 11:31:21.630471 140562938197696 TableScan.cpp:537]   col[4] n0_4 encoding=DICTIONARY leafSize=121 leafRetained=3392 actualBytes=43008 row{min=6 max=6 med=6 avg=6 cnt=7168} dict{min=6 max=6 med=6 avg=6 cnt=121}
W20260402 11:31:21.630530 140562938197696 TableScan.cpp:537]   col[5] n0_5 encoding=DICTIONARY leafSize=392 leafRetained=12096 actualBytes=43008 row{min=6 max=6 med=6 avg=6 cnt=7168} dict{min=6 max=6 med=6 avg=6 cnt=392}
W20260402 11:31:21.630586 140562938197696 TableScan.cpp:537]   col[6] n0_6 encoding=DICTIONARY leafSize=14 leafRetained=576 actualBytes=43008 row{min=6 max=6 med=6 avg=6 cnt=7168} dict{min=6 max=12 med=6 avg=8 cnt=14}
W20260402 11:31:21.630645 140562938197696 TableScan.cpp:537]   col[7] n0_7 encoding=DICTIONARY leafSize=120 leafRetained=3904 actualBytes=86020 row{min=12 max=16 med=12 avg=12 cnt=7168} dict{min=5 max=24 med=12 avg=11 cnt=120}
W20260402 11:31:21.630746 140562938197696 TableScan.cpp:537]   col[8] n0_8 encoding=DICTIONARY leafSize=390 leafRetained=16192 actualBytes=43146 row{min=6 max=12 med=6 avg=6 cnt=7168} dict{min=3 max=25 med=12 avg=11 cnt=390}
W20260402 11:31:21.630876 140562938197696 TableScan.cpp:537]   col[12] n0_12 encoding=DICTIONARY leafSize=2 leafRetained=64 actualBytes=14336 row{min=2 max=2 med=2 avg=2 cnt=7168} dict{min=0 max=2 med=2 avg=1 cnt=2}
W20260402 11:31:21.630958 140562938197696 TableScan.cpp:537]   col[13] n0_13 encoding=DICTIONARY leafSize=2 leafRetained=64 actualBytes=43008 row{min=6 max=6 med=6 avg=6 cnt=7168} dict{min=0 max=6 med=6 avg=3 cnt=2}
W20260402 11:31:21.631287 140562938197696 TableScan.cpp:537]   col[14] n0_14 encoding=DICTIONARY leafSize=33 leafRetained=1088 actualBytes=43008 row{min=6 max=6 med=6 avg=6 cnt=7168} dict{min=6 max=6 med=6 avg=6 cnt=33}
W20260402 11:31:21.631527 140562938197696 TableScan.cpp:537]   col[15] n0_15 encoding=DICTIONARY leafSize=33 leafRetained=1344 actualBytes=67890 row{min=9 max=24 med=9 avg=9 cnt=7168} dict{min=9 max=24 med=9 avg=11 cnt=33}
W20260402 11:31:21.631988 140562938197696 TableScan.cpp:537]   col[16] n0_16 encoding=DICTIONARY leafSize=369 leafRetained=10048 actualBytes=43008 row{min=6 max=6 med=6 avg=6 cnt=7168} dict{min=6 max=6 med=6 avg=6 cnt=369}
W20260402 11:31:21.632134 140562938197696 TableScan.cpp:537]   col[17] n0_17 encoding=DICTIONARY leafSize=369 leafRetained=12096 actualBytes=68676 row{min=9 max=33 med=9 avg=9 cnt=7168} dict{min=9 max=33 med=9 avg=11 cnt=369}
W20260402 11:31:21.632254 140562938197696 TableScan.cpp:537]   col[18] n0_18 encoding=DICTIONARY leafSize=8 leafRetained=256 actualBytes=46665 row{min=6 max=9 med=6 avg=6 cnt=7131} dict{min=3 max=9 med=6 avg=5 cnt=8}
W20260402 11:31:21.632408 140562938197696 TableScan.cpp:537]   col[19] n0_19 encoding=DICTIONARY leafSize=2785 leafRetained=98112 actualBytes=65760 row{min=6 max=33 med=9 avg=9 cnt=7168} dict{min=6 max=45 med=9 avg=9 cnt=2785}
W20260402 11:31:21.632512 140562938197696 TableScan.cpp:537]   col[20] n0_20 encoding=DICTIONARY leafSize=7 leafRetained=320 actualBytes=86016 row{min=12 max=12 med=12 avg=12 cnt=7168} dict{min=12 max=12 med=12 avg=12 cnt=7}
W20260402 11:31:21.633225 140562938197696 TableScan.cpp:537]   col[22] n0_22 encoding=DICTIONARY leafSize=32062 leafRetained=2096960 actualBytes=351232 row{min=49 max=49 med=49 avg=49 cnt=7168} dict{min=1 max=294 med=36 avg=39 cnt=32062}
W20260402 11:31:21.633310 140562938197696 TableScan.cpp:537]   col[23] n0_23 encoding=DICTIONARY leafSize=4 leafRetained=192 actualBytes=43008 row{min=6 max=6 med=6 avg=6 cnt=7168} dict{min=3 max=7 med=6 avg=4 cnt=4}
W20260402 11:31:21.633367 140562938197696 TableScan.cpp:537]   col[24] n0_24 encoding=DICTIONARY leafSize=2 leafRetained=64 actualBytes=43008 row{min=6 max=6 med=6 avg=6 cnt=7168} dict{min=4 max=6 med=6 avg=5 cnt=2}
W20260402 11:31:21.633424 140562938197696 TableScan.cpp:537]   col[25] n0_25 encoding=DICTIONARY leafSize=11 leafRetained=448 actualBytes=50176 row{min=7 max=7 med=7 avg=7 cnt=7168} dict{min=6 max=14 med=8 avg=8 cnt=11}
W20260402 11:31:21.633702 140562938197696 TableScan.cpp:537]   col[26] n0_26 encoding=DICTIONARY leafSize=18545 leafRetained=786240 actualBytes=114688 row{min=16 max=16 med=16 avg=16 cnt=7168} dict{min=0 max=20 med=16 avg=14 cnt=18545}
W20260402 11:31:21.634233 140562938197696 TableScan.cpp:537]   col[28] n0_28 encoding=DICTIONARY leafSize=26429 leafRetained=1572672 actualBytes=279552 row{min=39 max=39 med=39 avg=39 cnt=7168} dict{min=2 max=86 med=24 avg=26 cnt=26429}
W20260402 11:31:21.634307 140562938197696 TableScan.cpp:537]   col[31] n0_31 encoding=DICTIONARY leafSize=17 leafRetained=576 actualBytes=43008 row{min=6 max=6 med=6 avg=6 cnt=7168} dict{min=6 max=18 med=12 avg=9 cnt=17}
W20260402 11:31:21.634369 140562938197696 TableScan.cpp:537]   col[33] n0_33 encoding=DICTIONARY leafSize=128 leafRetained=5952 actualBytes=86016 row{min=12 max=12 med=12 avg=12 cnt=7168} dict{min=5 max=24 med=12 avg=11 cnt=128}
W20260402 11:31:21.634432 140562938197696 TableScan.cpp:537]   col[35] n0_35 encoding=DICTIONARY leafSize=412 leafRetained=16192 actualBytes=93184 row{min=13 max=13 med=13 avg=13 cnt=7168} dict{min=3 max=36 med=12 avg=12 cnt=412}
W20260402 11:31:21.634509 140562938197696 TableScan.cpp:537]   col[36] n0_36 encoding=DICTIONARY leafSize=441 leafRetained=32576 actualBytes=250880 row{min=35 max=35 med=35 avg=35 cnt=7168} dict{min=3 max=64 med=34 avg=35 cnt=441}
W20260402 11:31:21.634917 140562938197696 TableScan.cpp:537]   col[37] n0_37 encoding=DICTIONARY leafSize=51751 leafRetained=5242688 actualBytes=1654797312 row{min=230859 max=230859 med=230859 avg=230859 cnt=7168} dict{min=0 max=603479 med=19 avg=67 cnt=51751}
W20260402 11:31:21.635018 140562938197696 TableScan.cpp:537]   col[38] n0_38 encoding=DICTIONARY leafSize=4 leafRetained=192 actualBytes=43008 row{min=6 max=6 med=6 avg=6 cnt=7168} dict{min=4 max=10 med=7 avg=6 cnt=4}
W20260402 11:31:21.635243 140562938197696 TableScan.cpp:537]   col[39] n0_39 encoding=DICTIONARY leafSize=3 leafRetained=128 actualBytes=0 row{min=0 max=0 med=0 avg=0 cnt=7168} dict{min=0 max=12 med=1 avg=4 cnt=3}
W20260402 11:31:21.635382 140562938197696 TableScan.cpp:537]   col[41] n0_41 encoding=DICTIONARY leafSize=1113 leafRetained=40768 actualBytes=71680 row{min=10 max=10 med=10 avg=10 cnt=7168} dict{min=0 max=10 med=10 avg=9 cnt=1113}
W20260402 11:31:21.635519 140562938197696 TableScan.cpp:537]   col[43] n0_43 encoding=DICTIONARY leafSize=910 leafRetained=32576 actualBytes=71680 row{min=10 max=10 med=10 avg=10 cnt=7168} dict{min=0 max=10 med=10 avg=9 cnt=910}
W20260402 11:31:21.635647 140562938197696 TableScan.cpp:537]   col[49] n0_49 encoding=FLAT leafSize=7168 leafRetained=5436800 actualBytes=5117952 row{min=714 max=714 med=714 avg=714 cnt=7168} dict{min=714 max=714 med=714 avg=714 cnt=7168}
W20260402 11:31:21.635799 140562938197696 TableScan.cpp:537]   col[54] n0_54 encoding=DICTIONARY leafSize=1122 leafRetained=40768 actualBytes=71680 row{min=10 max=10 med=10 avg=10 cnt=7168} dict{min=0 max=10 med=10 avg=9 cnt=1122}
W20260402 11:31:21.635921 140562938197696 TableScan.cpp:537]   col[55] n0_55 encoding=DICTIONARY leafSize=1166 leafRetained=48960 actualBytes=71680 row{min=10 max=10 med=10 avg=10 cnt=7168} dict{min=0 max=10 med=10 avg=9 cnt=1166}
W20260402 11:31:21.635954 140562938197696 TableScan.cpp:537]   col[59] n0_59 encoding=DICTIONARY leafSize=3 leafRetained=192 actualBytes=0 row{min=0 max=0 med=0 avg=0 cnt=0} dict{min=4 max=13 med=7 avg=8 cnt=3}
W20260402 11:31:21.635963 140562938197696 TableScan.cpp:475]   col[60] n0_60 encoding=CONSTANT leafEncoding=CONSTANT (skipped)

```

### Expected Behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by zhangxffff**
### What problem does this PR solve?

Issue Number: close #406 

### Type of Change

- [x] 🐛 Bug fix (non-breaking change which fixes an issue)
- [ ] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🚀 Performance improvement (optimization)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🔨 Refactoring (no logic changes)
- [ ] 🔧 Build/CI or Infrastructure changes
- [ ] 📝 Documentation only

### Description

In the current ShuffleWriter or HashAgg, when we need to reserve memory, we cannot accurately estimate the flat memory cost of a Vector. Currently, we use `estimateFlatSize` to obtain an estimated value, which computes an average row size from the leaf vector's `retainedSize` (capacity-based) and scales it by the number of rows. For fixed-width types, this may be good enough, but for `StringView`, due to the variable length of strings, the average-based scaling does not account for the actual distribution of string sizes among the referenced rows. As a result, the estimated total size may be far off from the real size — under-estimation can cause OOM when processing these Vectors, while over-estimation can cause premature spilling and reduced performance.

However, if we take a deeper look at how we build a `FlatVector<StringView>` and how we use it, we can find a way to compute statistics with almost zero cost.

### How We Build a FlatVector\<StringView\>

There are many ways to create a `FlatVector<StringView>`:

1. Create a `FlatVector<StringView>` and populate it by vectorizing values from another data structure, such as:
   1. `DictionaryVector` via `flattenVector`
   2. Another `FlatVector<StringView>` via copy
   3. `RowContainer` via `extractColumn`
   4. Serialized spilled data via `PrestoSerializer`/`ArrowSerializer`
   5. `ArrowVector` via `ImportFromArrow`
   6. `CompactRow`/`UnsafeRow` via deserializer
   7. Serialized shuffle data via `ShuffleReader` deserializer
2. Create a `FlatVector<StringView>` and manipulate values by index — mainly in expressions.

For case 1, we can easily collect statistics while looping and building each `StringView`. We accumulate the total string data size during the loop and attach a `StringViewStat` to the `FlatVector<StringView>`. The stat is passed at construction time — there is no public setter on `FlatVector` to modify it after construction. For case 2, we keep `StringViewStat` as `nullopt`.

When calling `estimateFlatSize` on a `FlatVector<StringView>` that carries a `StringViewStat`, we can use it to obtain the exact total data size of all `StringView`s.

As a safety net, we add a debug-only assertion in mutation methods (`set()`, `setNoCopy()`, etc.) that fires if the stat is present:

```cpp
void set(vector_size_t idx, StringView value) {
  BOLT_DCHECK(!stringViewStat_.has_value(), "Mutating a FlatVector with StringViewStat");
  ...
}
```

This has zero overhead in release builds while catching invariant violations during development and testing.

Another concern is whether there are situations where we build a `FlatVector<StringView>` via case 1 and later manipulate its values by index as in case 2.

Fortunately, no such usage currently exists in Bolt. All `FlatVector<StringView>` instances created via case 1 are passed directly to the next Operator without further modification, and all `FlatVector<StringView>` instances manipulated via case 2 are created within their own Operator. Therefore, the statistics are reliable and can be trusted. The debug assertion above guards against future violations of this invariant.

### Why Only `flattenVector` and `copy` Need Statistics

Not all case 1 sub-cases need statistics. The key issue is how string buffers are managed.

For cases 1.3 through 1.7 (RowContainer, PrestoSerializer, ImportFromArrow, CompactRow, ShuffleReader), each path creates its **own** string buffers containing only the data the vector actually references. String data is either allocated with exact sizing (e.g., PrestoSerializer uses `getRawStringBufferWithSpace(dataSize, true /*exactSize*/)`), zero-copy wrapped with tight bounds (e.g., ImportFromArrow, ShuffleReader), or sequentially filled via `getRawStringBufferWithSpace` where buffer `size()` closely tracks actual usage (e.g., RowContainer, CompactRow). In all these cases, `retainedSize()` is already very close to the actual data size, so `estimateFlatSize` is accurate enough without additional statistics.

Cases 1.1 (`flattenVector`) and 1.2 (`copy`) are different. When the source and target vectors share the same memory pool, `FlatVector<StringView>::copy()` does **not** duplicate string data. Instead, it calls `acquireSharedStringBuffers(source)`, which adds **all** of the source's string buffers to the new vector. The new vector's `StringView`s point directly into these shared buffers. As a result, `retainedSize()` includes the full capacity of all shared buffers, even though the vector may only reference a small fraction of the strings in those buffers. For example, if we flatten a `DictionaryVector` that selects 100 rows from a `FlatVector<StringView>` with 10,000 rows and 100MB of string buffers, the resulting flat vector's `retainedSize` would be ~100MB, while the actual referenced data might only be ~1MB.

Therefore, we only need to collect statistics for `flattenVector` and `copy`. During these operations, we accumulate the total string data size of the actually referenced `StringView`s and attach a `StringViewStat` to the resulting `FlatVector<StringView>`. The stat is passed at construction time — there is no public setter on `FlatVector` to modify it after construction. For case 2 and for cases 1.3–1.7 (where `retainedSize` is already accurate), we keep `StringViewStat` as `nullopt` and fall back to the existing `retainedSize`-based estimation.

When calling `estimateFlatSize` on a `FlatVector<StringView>` that carries a `StringViewStat`, we can use it to obtain the exact total data size of all `StringView`s.

### Performance Impact

- [x] **No Impact**: This change does not affect the critical path (e.g., build system, doc, error handling).
```
  A/B Comparison: flattenVector with/without StringViewStats (Release, 2000 iters, 10000 rows)

  ┌────────┬──────────────────────┬─────────────────────────┬────────────┐
  │ strLen │ WITH stats (us/iter) │ WITHOUT stats (us/iter) │    Diff    │
  ├────────┼──────────────────────┼─────────────────────────┼────────────┤
  │ 16B    │ 17                   │ 17                      │ 0%         │
  ├────────┼──────────────────────┼─────────────────────────┼────────────┤
  │ 64B    │ 17                   │ 17                      │ 0%         │
  ├────────┼──────────────────────┼─────────────────────────┼────────────┤
  │ 256B   │ 18                   │ 17                      │ +1us (+6%) │
  ├────────┼──────────────────────┼─────────────────────────┼────────────┤
  │ 1KB    │ 18                   │ 18                      │ 0%         │
  ├────────┼──────────────────────┼─────────────────────────┼────────────┤
  │ 4KB    │ 18                   │ 19                      │ -1us (-5%) │
  ├────────┼──────────────────────┼─────────────────────────┼────────────┤
  │ 64KB   │ 30                   │ 31                      │ -1us (-3%) │
  └────────┴──────────────────────┴─────────────────────────┴────────────┘
```
- [ ] **Positive Impact**: I have run benchmarks.
    <details>
    <summary>Click to view Benchmark Results</summary>

    ```text
    Paste your google-benchmark or TPC-H results here.
    Before: 10.5s
    After:   8.2s  (+20%)
    ```
    </details>
- [ ] **Negative Impact**: Explained below (e.g., trade-off for correctness).

### Release Note

Please describe the changes in this PR

Release Note:

```text
Release Note:
- Fixed a crash in `substr` when input is null.
- optimized `group by` performance by 20%.
```

### Checklist (For Author)

- [x] I have added/updated unit tests (ctest).
- [x] I have verified the code with local build (Release/Debug).
- [x] I have run clang-format / linters.
- [ ] (Optional) I have run Sanitizers (ASAN/TSAN) locally for complex C++ changes.
- [ ] No need to test or manual test.

### Breaking Changes

- [ ] No
- [ ] Yes (Description: ...)
    <details>
    <summary>Click to view Breaking Changes</summary>

    ```text
    Breaking Changes:
    - Description of the breaking change.
    - Possible solutions or workarounds.
    - Any other relevant information.
    ```
    </details>

### CODE REVIEW

File: bolt/vector/FlatVector.cpp [hunk 1]
```diff
@@ -333,13 +368,19 @@ void FlatVector<StringView>::copy(
           bits::clearNull(rawNulls, row);
         }
         auto v = decoded.valueAt<StringView>(sourceRow);
+        statsTotalBytes += v.size();
```
Comment (guhaiyan0221) [inline bolt/vector/FlatVector.cpp]: which is more accuracy ? statsTotalBytes  or the following totalBytes ?  seems we do not need the statsTotalBytes, since if inline, size is fixed 16 bytes

Comment (zhangxffff) [reply bolt/vector/FlatVector.cpp]: Hmm, there is a subtle difference with statsTotalBytes — it includes the inline portion of the string size, which can be confusing. It would be better to align the behavior and exclude inline string sizes from the count. Has already fixed in latest commit.

**Review by guhaiyan0221 — APPROVED** [review]

File: bolt/vector/FlatVector-inl.h [hunk 2]
```diff
@@ -326,6 +362,15 @@ void FlatVector<T>::copyValuesAndNulls(
       });
     }
   }
+
+  if constexpr (std::is_same_v<T, StringView>) {
+    // Only set stats when copying all rows, otherwise stats would be
+    // partial and misleading.
+    if (kAllSelected) {
+      this->setStringViewStats(
```
Comment (markjin1990) [inline bolt/vector/FlatVector-inl.h:371]: @zhangxffff In case `source->isFlatEncoding` is true, `stringStatsTotal` and `stringStatsMax` are all 0, if we set setStringViewStats, won't `estimateFlatSize()` return all 0 (underestimate)?

Comment (zhangxffff) [reply bolt/vector/FlatVector-inl.h:371]: Yes, it is a problem. `stringStatsTotal` may be 0 here, add condition that only `setStringViewStats` when `stringStatsTotal` is not zero
