### PR TITLE
fix: try catch execptions in folly::guard

### LINKED ISSUE #141: [Bug] core dump from folly::gurad
### Component Selection

- [x] Core Engine (Expression eval, Memory, Vector)
- [ ] Connectors / File Formats (Hive, Parquet, etc.)
- [ ] API / Bindings (Python, etc.)
- [ ] Build
- [ ] Other

### Describe the Bug

```
This program will now terminate because a folly::ScopeGuard callback threw an 

exception.

terminate called after throwing an instance of 'std::system_error'

  what():  Invalid argument

```

### Reproduction Steps

unstablely occur

### Bolt Version / Commit ID

main

### System Configuration

```markdown
- **OS**: (e.g. Ubuntu 22.04, CentOS 7)
- **Compiler**: (e.g. GCC 11, Clang 14)
- **Build Type**: (Debug / Release / RelWithDebInfo)
- **CPU Arch**: (e.g. x86_64 AVX2, ARM64)
- **Framework**: (e.g. Spark 3.3, PrestoDB)

ubuntu
```

### Logs / Stack Trace

```shell

```

### Expected Behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by fzhedu**
### What problem does this PR solve?

Issue Number: close #141 , #147 

### Type of Change

- [x] 🐛 Bug fix (non-breaking change which fixes an issue)
- [ ] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🚀 Performance improvement (optimization)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🔨 Refactoring (no logic changes)
- [ ] 🔧 Build/CI or Infrastructure changes
- [ ] 📝 Documentation only

### Description

Describe your changes in detail.
For complex logic, explain the "Why" and "How".
Why: 
1. 
```
This program will now terminate because a folly::ScopeGuard callback threw an 

exception.

terminate called after throwing an instance of 'std::system_error'

  what():  Invalid argument

```

2. report asan use-after-free

How: 
1. try cache possible exceptions for folly gurad
2. fix use-after-free in tableScan::preload()

### Performance Impact

- [x] **No Impact**: This change does not affect the critical path (e.g., build system, doc, error handling).
- [ ] **Positive Impact**: I have run benchmarks.
    <details>
    <summary>Click to view Benchmark Results</summary>

    ```text
    Paste your google-benchmark or TPC-H results here.
    Before: 10.5s
    After:   8.2s  (+20%)
    ```
    </details>
- [ ] **Negative Impact**: Explained below (e.g., trade-off for correctness).

### Release Note

Please describe the changes in this PR

Release Note:

```text
Release Note:
- Fixed a core from folly::guard
- Fixed a use-after-free in tableScan::preload()
```

### Checklist (For Author)

- [ ] I have added/updated unit tests (ctest).
- [x] I have verified the code with local build (Release/Debug).
- [ ] I have run clang-format / linters.
- [ ] (Optional) I have run Sanitizers (ASAN/TSAN) locally for complex C++ changes.
- [ ] No need to test or manual test.

### Breaking Changes

- [x] No
- [ ] Yes (Description: ...)
    <details>
    <summary>Click to view Breaking Changes</summary>

    ```text
    Breaking Changes:
    - Description of the breaking change.
    - Possible solutions or workarounds.
    - Any other relevant information.
    ```
    </details>

### CODE REVIEW

File: bolt/common/caching/AsyncDataCache.cpp [hunk 1]
```diff
@@ -736,7 +736,11 @@ bool AsyncDataCache::makeSpace(
   // 'acquired' is not managed by a pool. Make sure it is freed on throw.
   // Destruct without pool and non-empty kills the process.
   auto guard = folly::makeGuard([&]() {
-    allocator_->freeNonContiguous(acquired);
+    try {
+      allocator_->freeNonContiguous(acquired);
+    } catch (...) {
```
Comment (wangxinshuo-bolt) [inline bolt/common/caching/AsyncDataCache.cpp]: Is it reasonable to catch all exceptions?

File: bolt/dwio/common/DirectBufferedInput.cpp [hunk 2]
```diff
@@ -247,8 +247,13 @@ void DirectBufferedInput::readRegions(
             return;
           }
           // the load is valid, so asyncThreadCtx is not freed yet.
-          auto guard =
-              folly::makeGuard([&]() { asyncLoad.asyncThreadCtx->out(); });
+          auto guard = folly::makeGuard([&]() {
+            try {
+              asyncLoad.asyncThreadCtx->out();
+            } catch (...) {
```
Comment (wangxinshuo-bolt) [inline bolt/dwio/common/DirectBufferedInput.cpp]: Can we `catch (std::exception& e)` and then print more details about the exception?

File: bolt/common/caching/AsyncDataCache.cpp (hunk 1 above)
Comment (fzhedu) [reply bolt/common/caching/AsyncDataCache.cpp]: yes, the guard can do nothing, just print the exception msg.

File: bolt/dwio/common/DirectBufferedInput.cpp (hunk 2 above)
Comment (fzhedu) [reply bolt/dwio/common/DirectBufferedInput.cpp]: ok

**Review by wangxinshuo-bolt — APPROVED** [review]
LGTM
