### PR TITLE
[ut][shuffle] Add shuffle ut framework and fix row based shuffle OOM

### LINKED ISSUE #74: [Chore] Improve unit test coverage for bolt shuffle
### Chore Type

Test Infrastructure

### Task Description

Bolt ShuffleWriter was derived from Gluten’s ShuffleWriter, but most of the related unit tests currently live in Gluten. We need to increase unit test coverage in Bolt ShuffleWriter to match the shuffle modes we support today, including V1, V2, and row-based shuffle, as well as scenarios involving CompositeRowVector and RSS.

### Motivation / Benefit

Adding these tests strengthens our regression guardrails for shuffle correctness across multiple execution paths.

### Related Files (Optional)

_No response_

### Implementation Plan (Optional)

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by zhangxffff**
### What problem does this PR solve?

Issue Number: close #74 and #72 

### Type of Change

- [x] 🐛 Bug fix (non-breaking change which fixes an issue)
- [ ] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🚀 Performance improvement (optimization)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🔨 Refactoring (no logic changes)
- [x] 🔧 Build/CI or Infrastructure changes
- [ ] 📝 Documentation only

### Description

Add shuffle unitttest, support a combine of these mode:
1. shuffle partitioning: Single, RoundRobin, Hash, Range
2. shuffle mode: Adaptive, V1, V2, RowBased
3. mapper number: 1, 4, 16
4. reducer number: 1, 4, 64
5. different input types: including all types, empty data and nulls

Fix:
1. Fix `FallbackRangePartitioner` `precompute`/`fill` not implement
2. Fix `ListenableArbitrator::shrinkCapacity` `shrink` not call `reclaim`
3. Fix RowBasedShuffle OOM caused by under estimated RowVector size

### Performance Impact

- [x] **No Impact**: This change does not affect the critical path (e.g., build system, doc, error handling).
- [ ] **Positive Impact**: I have run benchmarks.
    <details>
    <summary>Click to view Benchmark Results</summary>

    ```text
    Paste your google-benchmark or TPC-H results here.
    Before: 10.5s
    After:   8.2s  (+20%)
    ```
    </details>
- [ ] **Negative Impact**: Explained below (e.g., trade-off for correctness).

### Checklist (For Author)

- [x] I have added/updated unit tests (ctest).
- [x] I have verified the code with local build (Release/Debug).
- [x] I have run clang-format / linters.
- [ ] (Optional) I have run Sanitizers (ASAN/TSAN) locally for complex C++ changes.
- [ ] No need to test or manual test.

### Breaking Changes

- [x] No
- [ ] Yes (Description: ...)
    <details>
    <summary>Click to view Breaking Changes</summary>

    ```text
    Breaking Changes:
    - Description of the breaking change.
    - Possible solutions or workarounds.
    - Any other relevant information.
    ```
    </details>

### CODE REVIEW

File: bolt/shuffle/sparksql/BoltRowBasedSortShuffleWriter.cpp [hunk 1]
```diff
@@ -139,13 +131,18 @@ arrow::Status BoltRowBasedSortShuffleWriter::split(
       RETURN_NOT_OK(partitioner_->compute(
           pidArr, rv->size(), row2Partition_, partition2RowCount_));
       strippedRv = getStrippedRowVectorWrapper(*rv);
-      setSplitState(SplitState::kSplit);
+    }
+    auto rowVectorWithStats = rowConverter_->getWithStats(strippedRv);
```
Comment (XinShuoWang) [inline bolt/shuffle/sparksql/BoltRowBasedSortShuffleWriter.cpp:135]: Use more precise memory values to avoid OOM?

File: bolt/shuffle/sparksql/tests/ShuffleMatrixTest.cpp [hunk 2]
```diff
@@ -0,0 +1,75 @@
...
+#include "bolt/shuffle/sparksql/tests/ShuffleTestBase.h"
+
+namespace bytedance::bolt::shuffle::sparksql::test {
+
+std::vector<ShuffleTestParam> buildShuffleParams() {
+  std::vector<ShuffleTestParam> params;
+  const std::vector<std::string> partitionings = {
+      "single", "rr", "hash", "range"};
+  const std::vector<int32_t> shuffleModes = {0, 1, 2, 3};
+  const std::vector<int32_t> partitionNumbers = {1, 4, 16};
```
Comment (XinShuoWang) [inline bolt/shuffle/sparksql/tests/ShuffleMatrixTest.cpp:26]: Can PartitionNumber be made a bit larger? A higher PartitionNumber might trigger more special logic.

File: bolt/shuffle/sparksql/BoltRowBasedSortShuffleWriter.cpp (hunk 1 above)
Comment (zhangxffff) [reply bolt/shuffle/sparksql/BoltRowBasedSortShuffleWriter.cpp:135]: Yes, align the memory calculation logic between `maybeReserve` and the final allocation in `rowConverter_` to ensure we reserve the exact amount of memory required.

File: bolt/shuffle/sparksql/tests/ShuffleMatrixTest.cpp (hunk 2 above)
Comment (zhangxffff) [reply bolt/shuffle/sparksql/tests/ShuffleMatrixTest.cpp:26]: > Can PartitionNumber be made a bit larger? A higher PartitionNumber might trigger more special logic.

Thanks for your comments. I added a new test class `ShuffleLargePartitionTest` to cover large partition counts (1024). While doing this, I noticed that the memory limit logic in `TestMemoryManagerHolder` only applies through memory isolation, whereas the pool size in `ExecutionMemoryPool` is still set to `kMaxMemory`. We now use `ExecutionMemoryPool` to enforce memory limits with memory isolation disabled, which matches the default behavior in Gluten.

Please review the new code when you have time.

**Comment by XinShuoWang** [comment]
@zhangxffff I merged your commit, but the CI is broken. It doesn't seem to be caused by your commit, but rather related to JIT. I'll report it first for further investigation. cc @kexianda 

ci history: https://github.com/bytedance/bolt/actions/runs/21018261347/job/60427654064

**Comment by XinShuoWang** [comment]
@kexianda has fixed this problem in https://github.com/bytedance/bolt/pull/128

> @zhangxffff I merged your commit, but the CI is broken. It doesn't seem to be caused by your commit, but rather related to JIT. I'll report it first for further investigation. cc @kexianda
> 
> ci history: https://github.com/bytedance/bolt/actions/runs/21018261347/job/60427654064
