### PR TITLE
[bugfix] error: control reaches end of non-void function in SplitFunctions.cpp in debug mode

### LINKED ISSUE #99: [Build] build failure "/bolt/bolt/bolt/functions/sparksql/SplitFunctions.cpp:226:1: error: control reaches end of non-void function" in debug mode
### Summary of the Build Issue

Encountered a build failure when building `bolt_functions_spark_impl` when building under debug mode.

### Build Command

```shell
make debug
```

### Build Environment (Crucial)

- **OS**:  Ubuntu 22.04
- **Compiler**: GCC 11.4.0
- **Conan Version**: 2.22.2
- **CMake Version**: 3.22.1
- **Ninja Version**: 1.10.1
- **Python Version**: 3.10.12

### Conan Profile / Settings (Optional but Recommended)

```toml

```

### Error Log / Output

/bolt/bolt/bolt/functions/sparksql/SplitFunctions.cpp:226:1: error: control reaches end of non-void function [-Werror=return-type]
  226 | }
      | ^
cc1plus: some warnings being treated as errors

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by markjin1990**
### What problem does this PR solve?

Issue Number: close #99

### Type of Change

- [x] 🐛 Bug fix (non-breaking change which fixes an issue)
- [ ] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🚀 Performance improvement (optimization)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🔨 Refactoring (no logic changes)
- [ ] 🔧 Build/CI or Infrastructure changes
- [ ] 📝 Documentation only

### Description

- Move `limit` before `return`. Otherwise, it is not executable.
- Add unit test for split for cases like split(c0, c1, 2). Without testing this test case, the code path won't even be reached, and it is exactly why we never hit this problem before.

### Performance Impact

- [x] **No Impact**: This change does not affect the critical path (e.g., build system, doc, error handling).
- [ ] **Positive Impact**: I have run benchmarks.
    <details>
    <summary>Click to view Benchmark Results</summary>

    ```text
    Paste your google-benchmark or TPC-H results here.
    Before: 10.5s
    After:   8.2s  (+20%)
    ```
    </details>
- [ ] **Negative Impact**: Explained below (e.g., trade-off for correctness).

### Release Note

Please describe the changes in this PR

Release Note:

```text
Release Note:
- Move `limit` before `return`. Otherwise, build in debug mode fails with error "control reaches end of non-void function in SplitFunctions.cpp"
- Added a unit test.
```

### Checklist (For Author)

- [x] I have added/updated unit tests (ctest).
- [x] I have verified the code with local build (Release/Debug).
- [x] I have run clang-format / linters.
- [ ] (Optional) I have run Sanitizers (ASAN/TSAN) locally for complex C++ changes.
- [ ] No need to test or manual test.

### Breaking Changes

- [x] No
- [ ] Yes (Description: ...)
    <details>
    <summary>Click to view Breaking Changes</summary>

    ```text
    Breaking Changes:
    - Description of the breaking change.
    - Possible solutions or workarounds.
    - Any other relevant information.
    ```
    </details>

### CODE REVIEW

File: bolt/connectors/hive/HiveDataSource.cpp [hunk 1]
```diff
@@ -200,7 +200,7 @@ HiveDataSource::HiveDataSource(
   }
   auto remainingFilter = hiveTableHandle_->remainingFilter();
   if (hiveTableHandle_->isFilterPushdownEnabled()) {
-    remainingFilter = extractFiltersFromRemainingFilter(
+    remainingFilter = hive::extractFiltersFromRemainingFilter(
```
Comment (ZacBlanco) [inline bolt/connectors/hive/HiveDataSource.cpp:203]: Is this change intentional?

Comment (markjin1990) [reply bolt/connectors/hive/HiveDataSource.cpp:203]: @ZacBlanco yes, it is irrelevant to this PR. Since it is very trivial, only affecting our internal build but not OSS, I simply add it here, instead of creating a new issue.
