### PR TITLE
fix(parquet): propagate ConvertedType to ScanSpec and enable VARCHAR pruning fallback when LogicalType or ConvertedType is absent

### LINKED ISSUE #241: [Bug] Parquet: ConvertedType not propagated to ScanSpec; fallback missing when LogicalType is absent
### Component Selection

- [ ] Core Engine (Expression eval, Memory, Vector)
- [x] Connectors / File Formats (Hive, Parquet, etc.)
- [ ] API / Bindings (Python, etc.)
- [ ] Build
- [ ] Other

### Describe the Bug

  - Many Parquet writers set legacy ConvertedType (e.g., UTF8) without v2 LogicalType.STRING.
  - Bolt reads the file, but LogicalType is absent, so logical-type collection is empty. Bolt does not surface ConvertedType into ScanSpec, leaving filtering and consumers without string semantics.

  Impact

  - Row-group pruning for VARCHAR columns is skipped because ScanSpec lacks string semantics.
  - Downstream logic expecting string context via ScanSpec cannot rely on ConvertedType when LogicalType is absent.

### Reproduction Steps

 - Use a file where a textual column is BYTE_ARRAY with ConvertedType=UTF8 and no v2 LogicalType.
 - Observe that ScanSpec.logicalTypeName() is empty and ScanSpec has no converted-type info, so ParquetData::filterRowGroups skips filtering for VARCHAR.

### Bolt Version / Commit ID

main

### System Configuration

```markdown
- **OS**: (e.g. Ubuntu 22.04, CentOS 7)
- **Compiler**: (e.g. GCC 11, Clang 14)
- **Build Type**: (Debug / Release / RelWithDebInfo)
- **CPU Arch**: (e.g. x86_64 AVX2, ARM64)
- **Framework**: (e.g. Spark 3.3, PrestoDB)
```

### Logs / Stack Trace

```shell

```

### Expected Behavior

When LogicalType is absent, ScanSpec.convertedTypeName() carries legacy string semantics (e.g., UTF8), enabling VARCHAR row-group pruning and consistent downstream handling.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by oarap**
### What problem does this PR solve?

Many Parquet files set legacy ConvertedType (e.g. UTF8) without v2 LogicalType.STRING. Bolt previously did not surface ConvertedType into ScanSpec, so VARCHAR columns lacked string semantics and row-group pruning was skipped when LogicalType was absent.

Issue Number: close #241

### Type of Change

- [x] 🐛 Bug fix (non-breaking change which fixes an issue)
- [ ] ✨ New feature (non-breaking change which adds functionality)
- [x] 🚀 Performance improvement (optimization)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🔨 Refactoring (no logic changes)
- [ ] 🔧 Build/CI or Infrastructure changes
- [ ] 📝 Documentation only

### Description

This change:
- Adds converted-type storage/accessors to ScanSpec and annotates specs with collected ConvertedType during schema initialization.
- Updates ParquetData::filterRowGroups to use ConvertedType as a fallback gate for VARCHAR columns when LogicalType is missing.
- Keeps LogicalType.STRING → VARCHAR mapping for byte-backed columns (if present) for consistency with the spec and other readers.

Outcome: VARCHAR columns gain correct pruning and downstream behavior even when only ConvertedType is present.

### Performance Impact

- [ ] **No Impact**: This change does not affect the critical path (e.g., build system, doc, error handling).
- [x] **Positive Impact**: I have run benchmarks.
    <details>
    <summary>Click to view Benchmark Results</summary>

    ```text
    Paste your google-benchmark or TPC-H results here.
    Before: 10.5s
    After:   8.2s  (+20%)
    ```
    </details>
- [ ] **Negative Impact**: Explained below (e.g., trade-off for correctness).

### Release Note

Please describe the changes in this PR

Release Note:

```text
Release Note:
- Fixed a crash in `substr` when input is null.
- optimized `group by` performance by 20%.
```

### Checklist (For Author)

- [x] I have added/updated unit tests (ctest).
- [x] I have verified the code with local build (Release/Debug).
- [x] I have run clang-format / linters.
- [ ] (Optional) I have run Sanitizers (ASAN/TSAN) locally for complex C++ changes.
- [ ] No need to test or manual test.

### Breaking Changes

- [x] No
- [ ] Yes (Description: ...)
    <details>
    <summary>Click to view Breaking Changes</summary>

    ```text
    Breaking Changes:
    - Description of the breaking change.
    - Possible solutions or workarounds.
    - Any other relevant information.
    ```
    </details>

### CODE REVIEW

File: bolt/dwio/parquet/reader/ParquetReader.cpp [hunk 1]
```diff
@@ -1315,6 +1347,19 @@ class ParquetRowReader::Impl {
           }
           spec.setLogicalTypeName(name);
         }
+        auto ctIt = ctMap.find(path);
+        if (ctIt != ctMap.end()) {
+          const auto name = thrift::to_string(ctIt->second);
+          if (!spec.convertedTypeName().empty() &&
+              spec.convertedTypeName() != name) {
+            BOLT_FAIL(fmt::format(
```
Comment (markjin1990) [inline bolt/dwio/parquet/reader/ParquetReader.cpp]: nip: we usually use `BOLT_CHECK()` instead of `if () {BOLT_FAIL()}`.
