### PR TITLE
[fix] Fix flaky assertion in MultiFragmentTest.partitionedOutputWithLargeInput

### LINKED ISSUE #349: [Bug] MultiFragmentTest.partitionedOutputWithLargeInput hangs
### Component Selection

- [ ] Core Engine (Expression eval, Memory, Vector)
- [ ] Connectors / File Formats (Hive, Parquet, etc.)
- [ ] API / Bindings (Python, etc.)
- [x] Build
- [ ] Other

### Describe the Bug

Occasionally when running tests in CI, we see the build pipeline stalls when running tests. Usually test runs take ~10 minutes, but sometimes it will hang for an hour and then fail. This consumes CI resources and delays valuable PR feedback.

The culprit seems to be `MultiFragmentTest.partitionedOutputWithLargeInput`. A sample fragment from the output log of a CI failure is reproduced below:

```
[       OK ] MultiFragmentTest.mergeExchange (2277 ms)
[ RUN      ] MultiFragmentTest.partitionedOutput
[       OK ] MultiFragmentTest.partitionedOutput (1620 ms)
[ RUN      ] MultiFragmentTest.partitionedOutputWithLargeInput
E20260302 07:06:12.811446 126393690085056 Exceptions.h:82] Line: /__w/bolt/bolt/bolt/common/memory/MemoryArbitrator.cpp:131, Function:growCapacity, Expression:  Exceeded memory pool capacity. Exceeded memory pool capacity.Can't grow default_root_239 capacity with 1.00MB. This will exceed its max capacity 1.00MB, current capacity 1.00MB.
Memory Pool[default_root_239 AGGREGATE root[default_root_239] parent[null] MALLOC track-usage thread-safe]<max capacity 1.00MB capacity 1.00MB used 980.00KB available 0B reservation [used 0B, reserved 1.00MB, min 0B] counters [allocs 0, frees 0, reserves 0, releases 0, collisions 0])>
default_root_239 usage 980.00KB reserved 1.00MB peak 1.00MB
    task.local://leaf-0 usage 980.00KB reserved 1.00MB peak 1.00MB
        node.1 usage 980.00KB reserved 1.00MB peak 1.00MB
            op.1.0.0.PartitionedOutput usage 980.00KB reserved 1.00MB peak 980.00KB

Top 1 leaf memory pool usages:
    op.1.0.0.PartitionedOutput usage 980.00KB reserved 1.00MB peak 980.00KB
, Source: RUNTIME, ErrorCode: MEM_CAP_EXCEEDED


99% tests passed, 1 tests failed out of 408

Label Time Summary:
celeborn_e2e    =   0.01 sec*proc (1 test)

Total Test time (real) = 3044.95 sec

The following tests did not run:
	 87 - */MemoryAllocatorTest.allocContiguousVsize/* (Disabled)
	125 - */MemoryCapExceededTest.singleDriver/* (Disabled)
	127 - */MemoryCapExceededTest.allocatorCapacityExceededError/* (Disabled)
	148 - */MemoryPoolTest.memoryLeakCheck/* (Disabled)
	187 - */MemoryPoolTest.concurrentUpdateToSharedPools/* (Disabled)
	279 - */SharedArbitrationTestWithThreadingModes.raceBetweenTaskTerminateAndReclaim/* (Disabled)

The following tests FAILED:
	401 - bolt_exec_test (Timeout)
make: *** [Makefile:362: unittest_release_spark] Error 8
Error: Process completed with exit code 2.

```

This shows that `MultiFragmentTest.partitionedOutputWithLargeInput` started, but never finished. There is one output log message about `MEM_CAP_EXCEEDED` but doesn't describe why the test hangs.

### Reproduction Steps

1. Create a PR
2. Run the CI 5-10 times
3. Observe runtime. It is likely to have at least one hang

### Bolt Version / Commit ID

4a3764b694071db6d82cfbb53835769a019bbe6b

### System Configuration

```markdown
CI machines
```

### Logs / Stack Trace

```shell
See above
```

### Expected Behavior

No hang. The test should either fail immediately, or pass in a reasonable time window.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by frankobe**
### What problem does this PR solve?

Issue Number: close #349 

### Type of Change

- [x] 🐛 Bug fix (non-breaking change which fixes an issue)
- [ ] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🚀 Performance improvement (optimization)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🔨 Refactoring (no logic changes)
- [x] 🔧 Build/CI or Infrastructure changes
- [ ] 📝 Documentation only

### Description

Describe your changes in detail.
For complex logic, explain the "Why" and "How".

The test was checking inputVectors on the consumer's Exchange operator, which is non-deterministic due to vector merging. Switch to checking outputVectors on the leaf task's PartitionedOutput operator instead, and wait for leaf task completion before reading stats.

### Performance Impact

- [x] **No Impact**: This change does not affect the critical path (e.g., build system, doc, error handling).
- [ ] **Positive Impact**: I have run benchmarks.
    <details>
    <summary>Click to view Benchmark Results</summary>

    ```text
    Paste your google-benchmark or TPC-H results here.
    Before: 10.5s
    After:   8.2s  (+20%)
    ```
    </details>
- [ ] **Negative Impact**: Explained below (e.g., trade-off for correctness).

### Release Note

Please describe the changes in this PR

Release Note:

```text
Release Note:
- Fix flaky assertion in MultiFragmentTest.partitionedOutputWithLargeInput
```

### Checklist (For Author)

- [x] I have added/updated unit tests (ctest).
- [x] I have verified the code with local build (Release/Debug).
- [ ] I have run clang-format / linters.
- [ ] (Optional) I have run Sanitizers (ASAN/TSAN) locally for complex C++ changes.
- [ ] No need to test or manual test.

### Breaking Changes

- [x] No
- [ ] Yes (Description: ...)
    <details>
    <summary>Click to view Breaking Changes</summary>

    ```text
    Breaking Changes:
    - Description of the breaking change.
    - Possible solutions or workarounds.
    - Any other relevant information.
    ```
    </details>

### CODE REVIEW

File: bolt/exec/tests/MultiFragmentTest.cpp [hunk 1]
```diff
@@ -604,10 +604,14 @@ TEST_F(MultiFragmentTest, partitionedOutputWithLargeInput) {
...
-    auto taskStats = toPlanStats(task->taskStats());
-    ASSERT_GT(taskStats.at("0").inputVectors, 2);
     ASSERT_TRUE(waitForTaskCompletion(leafTask.get()))
         << leafTask->taskId() << "state: " << leafTask->state();
+    // Check the leaf task's PartitionedOutput operator ("1") for outputVectors.
+    // Leaf plan: "0" = Values, "1" = PartitionedOutput.
+    // We avoid checking the consumer's Exchange inputVectors because the
+    // Exchange may merge small vectors, making the count non-deterministic.
+    auto taskStats = toPlanStats(leafTask->taskStats());
+    ASSERT_GT(taskStats.at("1").outputVectors, 2);
```
Comment (ZacBlanco) [inline bolt/exec/tests/MultiFragmentTest.cpp:613]: It seems like the `task` variable assigned by `assertQuery` is no longer used. Other than checking the output, I'm not sure it's required?

File: bolt/exec/tests/MultiFragmentTest.cpp [hunk 2]
```diff
@@ -645,12 +649,11 @@ TEST_F(MultiFragmentTest, partitionedOutputWithLargeInput) {
...
         op, intermediateTaskIds, "SELECT c0, c1, c2, c3, c4 FROM tmp");
-    auto taskStats = toPlanStats(task->taskStats());
-    // Disable this test as it flakes
-    // ASSERT_GT(taskStats.at("0").inputVectors, 2);
-
     ASSERT_TRUE(waitForTaskCompletion(leafTask.get()))
         << "state: " << leafTask->state();
+    // Same as above: check the leaf's PartitionedOutput operator ("1").
+    auto taskStats = toPlanStats(leafTask->taskStats());
+    ASSERT_GT(taskStats.at("1").outputVectors, 2);
```
Comment (ZacBlanco) [inline bolt/exec/tests/MultiFragmentTest.cpp:654]: Same here, `task` is no longer used?

File: bolt/exec/tests/MultiFragmentTest.cpp (hunk 1 above)
Comment (frankobe) [reply bolt/exec/tests/MultiFragmentTest.cpp:613]: @ZacBlanco nice catch. Removed.

**Comment by ZacBlanco** [comment]
The merge queue job failed with another test case inside MultiFragmentTest suite, but it seems there is a different root cause. It has occurred in other PRs too. This is the error reproduced below. I will file another bug 

```
[ RUN      ] MultiFragmentTest.morselDrivenTestSplitHashJoinWithExchangeOnBuildSide
E20260306 08:12:51.437994 140473258206912 Exceptions.h:82] Line: /__w/bolt/bolt/bolt/exec/ExchangeClient.cpp:54, Function:addRemoteTaskId, Expression:  Failed to create ExchangeSource: Testing error. Task ID: bad://leaf-1., Source: RUNTIME, ErrorCode: INVALID_STATE
E20260306 08:12:51.439588 140469489825472 Exceptions.h:82] Line: /__w/bolt/bolt/bolt/exec/ExchangeClient.cpp:54, Function:addRemoteTaskId, Expression:  Failed to create ExchangeSource: Testing error. Task ID: bad://leaf-0., Source: RUNTIME, ErrorCode: INVALID_STATE
E20260306 08:12:51.439948 140473771358528 Exceptions.h:82] Line: /__w/bolt/bolt/bolt/exec/ExchangeClient.cpp:54, Function:addRemoteTaskId, Expression:  Failed to create ExchangeSource: Testing error. Task ID: bad://leaf-1., Source: RUNTIME, ErrorCode: INVALID_STATE
unknown file: Failure
C++ exception with description "Exception: BoltRuntimeError
Error Source: RUNTIME
Error Code: INVALID_STATE
Reason: Failed to create ExchangeSource: Testing error. Task ID: bad://leaf-1.
Retriable: False
Function: addRemoteTaskId
File: /__w/bolt/bolt/bolt/exec/ExchangeClient.cpp
Line: 54
Stack trace:
# 0  _ZN9bytedance4bolt7process10StackTraceC1Ei
# 1  _ZN9bytedance4bolt13BoltExceptionC1EPKcmS3_St17basic_string_viewIcSt11char_traitsIcEES7_S7_S7_bNS1_4TypeES7_
# 2  _ZN9bytedance4bolt6detail13boltCheckFailINS0_16BoltRuntimeErrorERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEvRKNS1_17BoltCheckFailArgsET0_
# 3  _ZN9bytedance4bolt4exec14ExchangeClient15addRemoteTaskIdERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE.cold
# 4  _ZN9bytedance4bolt4exec4Task14addRemoteSplitERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS1_5SplitE
# 5  _ZN9bytedance4bolt4exec4Task8addSplitERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEONS1_5SplitE
# 6  _ZN9bytedance4bolt4exec12_GLOBAL__N_175MultiFragmentTest_morselDrivenTestSplitHashJoinWithExchangeOnBuildSide_Test8TestBodyEv
# 7  _ZN7testing8internal35HandleExceptionsInMethodIfSupportedINS_4TestEvEET0_PT_MS4_FS3_vEPKc
# 8  _ZN7testing4Test3RunEv
# 9  _ZN7testing8TestInfo3RunEv
# 10 _ZN7testing9TestSuite3RunEv
# 11 _ZN7testing8internal12UnitTestImpl11RunAllTestsEv
# 12 _ZN7testing8UnitTest3RunEv
# 13 main
# 14 0x0000000000000000
# 15 __libc_start_main
# 16 _start
" thrown in the test body.

[  FAILED  ] MultiFragmentTest.morselDrivenTestSplitHashJoinWithExchangeOnBuildSide (76 ms)
```
