### PR TITLE
[bugfix] port hash join tests: fix bugs about lazy vector inputs and support pushing down dynamic filter for right join

### LINKED ISSUE #41: [Bug] Filters on LazyVectors in Joins can lead to incorrect results
### Component Selection

- [x] Core Engine (Expression eval, Memory, Vector)
- [ ] Connectors / File Formats (Hive, Parquet, etc.)
- [ ] API / Bindings (Python, etc.)
- [ ] Build
- [ ] Other

### Describe the Bug

`SELECT t.c1, t.c2 FROM t LEFT JOIN u ON t.c0 = u.c0 AND (c1 > 0 AND c2 > 0) `get wrong results for lazy vectors.
```
Expected 1000, got 1000
43 extra rows, 43 missing rows
10 of extra rows:
	0 | 1
	0 | 1
	0 | 1
	0 | 1
	0 | 1
	0 | 1
	0 | 1
	0 | 1
	0 | 1
	0 | 1

10 of missing rows:
	0 | 0
	0 | 0
	0 | 2
	0 | 3
	0 | 4
	0 | 5
	0 | 5
	0 | 6
	0 | 6
	0 | 7
```

### Reproduction Steps

1. create table t(c0,c1,c2) and u(c0) with lazy vector inputs;
2. create the tests in the `HashJoinTest` 

### Bolt Version / Commit ID

main

### System Configuration

```markdown
- **OS**: (e.g. Ubuntu 22.04, CentOS 7)
- **Compiler**: (e.g. GCC 11, Clang 14)
- **Build Type**: (Debug / Release / RelWithDebInfo)
- **CPU Arch**: (e.g. x86_64 AVX2, ARM64)
- **Framework**: (e.g. Spark 3.3, PrestoDB)
```

### Logs / Stack Trace

```shell

```

### Expected Behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by fzhedu**
### What problem does this PR solve?

Issue Number: close #41 

### Type of Change

- [x] 🐛 Bug fix (non-breaking change which fixes an issue)
- [x] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🚀 Performance improvement (optimization)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🔨 Refactoring (no logic changes)
- [ ] 🔧 Build/CI or Infrastructure changes
- [ ] 📝 Documentation only

### Description

Describe your changes in detail. 
For complex logic, explain the "Why" and "How". 

Why: the lazy vectors may be not fully loaded, causing wrong results in join with filter.

How: fully load lazy vectors in filter of join. besides, pushing dow filters to right join.

### Performance Impact

- [x] **No Impact**: This change does not affect the critical path (e.g., build system, doc, error handling).
- [ ] **Positive Impact**: I have run benchmarks.
    <details>
    <summary>Click to view Benchmark Results</summary>

    ```text
    Paste your google-benchmark or TPC-H results here.
    Before: 10.5s
    After:   8.2s  (+20%)
    ```
    </details>
- [ ] **Negative Impact**: Explained below (e.g., trade-off for correctness).

### Release Note

Please describe the changes in this PR

Release Note:

```text
Release Note:
- fix bug when hash join with filter on lazy vectors
- support pushing down dynamic filters through right join
```

### Checklist (For Author)

- [x] I have added/updated unit tests (ctest).
- [x] I have verified the code with local build (Release/Debug).
- [x] I have run clang-format / linters.
- [ ] (Optional) I have run Sanitizers (ASAN/TSAN) locally for complex C++ changes.
- [ ] No need to test or manual test.

### Breaking Changes

- [x] No
- [ ] Yes (Description: ...)
    <details>
    <summary>Click to view Breaking Changes</summary>

    ```text
    Breaking Changes:
    - Description of the breaking change.
    - Possible solutions or workarounds.
    - Any other relevant information.
    ```
    </details>

### CODE REVIEW

File: bolt/exec/HashAggregation.cpp [hunk 1]
```diff
@@ -163,15 +163,11 @@ void HashAggregation::initialize() {
...
-    for (auto i = 0; i < hashers.size(); ++i) {
-      identityProjections_.emplace_back(hashers[i]->channel(), i);
-    }
-  } else {
-    addRuntimeStat("isDistinctAggregation", RuntimeCounter(0));
-  }
+  addRuntimeStat("isDistinctAggregation", RuntimeCounter(isDistinct_));
 
+  for (auto i = 0; i < hashers.size(); ++i) {
+    identityProjections_.emplace_back(hashers[i]->channel(), i);
```
Comment (guhaiyan0221) [inline bolt/exec/HashAggregation.cpp:169]: if isDistinct_ is false, identityProjections_ should also be filled?

Comment (fzhedu) [reply bolt/exec/HashAggregation.cpp:169]: yes, so that dynamic filters can be pushed down through agg, as the tests shows.

**Review by guhaiyan0221 — APPROVED** [review]
