### PR TITLE
fix: asyncThreadCtx may be use-after-free in canPreload()

### LINKED ISSUE #85: [Bug] heap-buffer-overflow error in canPreload() due to freed pointers
### Component Selection

- [x] Core Engine (Expression eval, Memory, Vector)
- [ ] Connectors / File Formats (Hive, Parquet, etc.)
- [ ] API / Bindings (Python, etc.)
- [ ] Build
- [ ] Other

### Describe the Bug

asan report

```
Address 0x61d0003ad218 is a wild pointer.
SUMMARY: AddressSanitizer: heap-buffer-overflow  in dwio::common::DirectBufferedInput::AsyncLoadHolder::canPreload() const
Shadow bytes around the buggy address:
  0x0c3a8006d9f0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c3a8006da00: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c3a8006da10: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c3a8006da20: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c3a8006da30: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
=>0x0c3a8006da40: fa fa fa[fa]fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c3a8006da50: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c3a8006da60: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c3a8006da70: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c3a8006da80: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c3a8006da90: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
```

### Reproduction Steps

run asan binary can occasionally occur this issue.

### Bolt Version / Commit ID

main

### System Configuration

```markdown
- **OS**: (e.g. Ubuntu 22.04, CentOS 7)
- **Compiler**: (e.g. GCC 11, Clang 14)
- **Build Type**: (Debug / Release / RelWithDebInfo)
- **CPU Arch**: (e.g. x86_64 AVX2, ARM64)
- **Framework**: (e.g. Spark 3.3, PrestoDB)

Ubuntu 22.04 on x86
```

### Logs / Stack Trace

```shell
asan stack
 
dwio::common::DirectBufferedInput::AsyncLoadHolder::canPreload() const
dwio::common::DirectBufferedInput::readRegions()
folly::ThreadPoolExecutor::runTask()
```

### Expected Behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by fzhedu**
### What problem does this PR solve?

Issue Number: close #85

### Type of Change

- [x] 🐛 Bug fix (non-breaking change which fixes an issue)
- [ ] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🚀 Performance improvement (optimization)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🔨 Refactoring (no logic changes)
- [ ] 🔧 Build/CI or Infrastructure changes
- [ ] 📝 Documentation only

### Description

Describe your changes in detail. 
For complex logic, explain the "Why" and "How". 

Why: the main thread may free the `asyncThreadCtx` and exit, then the async thread use `asyncThreadCtx` , resulting into errors.

How: check load'stats before use `asyncThreadCtx`.  It can significantly reduce the chance of the issue. There is still one rare case, the `asyncThreadCtx` is freed after checking state  before `asyncThreadCtx->in()`.

### Performance Impact

- [x] **No Impact**: This change does not affect the critical path (e.g., build system, doc, error handling).
- [ ] **Positive Impact**: I have run benchmarks.
    <details>
    <summary>Click to view Benchmark Results</summary>

    ```text
    Paste your google-benchmark or TPC-H results here.
    Before: 10.5s
    After:   8.2s  (+20%)
    ```
    </details>
- [ ] **Negative Impact**: Explained below (e.g., trade-off for correctness).

### Release Note

Please describe the changes in this PR

Release Note:

```text
Release Note:
- Fix asyncThreadCtx may be use-after-free in canPreload()
```

### Checklist (For Author)

- [ ] I have added/updated unit tests (ctest).
- [x] I have verified the code with local build (Release/Debug).
- [ ] I have run clang-format / linters.
- [x] (Optional) I have run Sanitizers (ASAN/TSAN) locally for complex C++ changes.
- [ ] No need to test or manual test.

### Breaking Changes

- [x] No
- [ ] Yes (Description: ...)
    <details>
    <summary>Click to view Breaking Changes</summary>

    ```text
    Breaking Changes:
    - Description of the breaking change.
    - Possible solutions or workarounds.
    - Any other relevant information.
    ```
    </details>

### CODE REVIEW

File: bolt/dwio/common/DirectBufferedInput.h [hunk 1]
```diff
@@ -309,7 +309,8 @@ class DirectBufferedInput : public BufferedInput {
     bool canPreload() const {
       static int maxAttempt = 1000;
       static int sleepMs = 500;
-      if (!asyncThreadCtx->allowPreload() || prefetchMemoryPercent_ == 0) {
+      if (load->state() != DirectCoalescedLoad::State::kPlanned ||
+          prefetchMemoryPercent_ == 0 || !asyncThreadCtx->allowPreload()) {
```
Comment (XinShuoWang) [inline bolt/dwio/common/DirectBufferedInput.h]: `prefetchMemoryPercent_ == 0` means user limited the memory used by prefetch manually?

**Review by wangxinshuo-bolt — APPROVED** [review]
LGTM

**Review by guhaiyan0221 — APPROVED** [review]
